#ifndef _EVENTDEFINE_H_
#define _EVENTDEFINE_H_
// 事件类型

//控件通用事件
#define EV_USER				50000
#define NC_COMMAND			0
#define NC_CREATE			100

#define UI_TIMER			200
#define UI_SWITCHENTER		201
#define UI_SWITCHLEAVE		202
#define UI_CREATE			203
#define UI_OWNERDRAW		204

// 鼠标
#define EV_MOUSEBASE		1000
#define EV_MOUSEMOVE		EV_MOUSEBASE+1
#define EV_MOUSEHOVER		EV_MOUSEBASE+2
#define EV_MOUSEENTER		EV_MOUSEBASE+3
#define EV_MOUSELEAVE		EV_MOUSEBASE+4
#define EV_MOUSELBTDOWN		EV_MOUSEBASE+5
#define EV_MOUSERBTDOWN		EV_MOUSEBASE+6
#define EV_MOUSEMBTDOWN		EV_MOUSEBASE+7
#define EV_MOUSELBTUP		EV_MOUSEBASE+8
#define EV_MOUSERBTUP		EV_MOUSEBASE+9
#define EV_MOUSEMBTUP		EV_MOUSEBASE+10
#define EV_MOUSEENVET_END	EV_MOUSEBASE+1000

// 键盘
#define EV_KEYBOARDBASE		1100
#define EV_KEYDOWN			EV_KEYBOARDBASE+1
#define EV_KEYUP			EV_KEYBOARDBASE+2
#define EV_KEYCHAR			EV_KEYBOARDBASE+3
#define EV_KEYENVET_END		EV_KEYBASE+1000

// 输入法
#define EV_IMEBASE			1200
#define EV_IMECOMP			EV_IMEBASE+1
#define EV_IMEENDCOMP		EV_IMEBASE+2
#define EV_IMENOTIFY		EV_IMEBASE+3
#define EV_IMEEVENT_END		EV_IMEBASE+1000

// 控件事件
#define EV_ELEMENTBASE		1300
#define EV_SETFOCUS			(EV_ELEMENTBASE+1)
#define EV_KILLFOCUS		(EV_ELEMENTBASE+2)
#define EV_WINDOWPOSCHANGE	(EV_ELEMENTBASE+3)

// 菜单
#define UPDATE_COMMAND_UI	1400

// 按钮
#define	EV_BUTTON_EVENTBASE	1500
#define	EV_BNCLICKED		(EV_BUTTON_EVENTBASE+1)
#define	EV_RBNCLICKED		(EV_BUTTON_EVENTBASE+2)

// ScrollBar
#define EV_SCROLL_EVENTBASE 1600
#define EV_SCROLLPOSCHANGED	(EV_SCROLL_EVENTBASE+1)

#define NC_SCROLL_CREATE	(EV_SCROLL_EVENTBASE+100)
#define EV_SCROLL_END		(EV_SCROLL_EVENTBASE+1000)

// Panel
#define EV_PANEL_EVENT_BASE	1700
#define EV_NC_POSCHANGED	(EV_PANEL_EVENT_BASE+1)

// ProgressBar
#define EV_PROGRESS_EVENT_BASE 1800
#define EV_POSCHANGE		(EV_PROGRESS_EVENT_BASE+1)

// Listbox
#define EV_LISTBOX_EVENT_BASE	1900
#define EV_SELCHANGE		(EV_LISTBOX_EVENT_BASE+1)
#endif // _EVENTDEFINE_H_