#ifndef _UIM_MESSAGE_H
#define _UIM_MESSAGE_H

enum
{
	UIM_MOVE,
	UIM_SIZE,
	UIM_ENABLE,
	UIM_SHOWWINDOW,
	UIM_KEYDOWN,
	UIM_KEYUP,
	UIM_CHAR,
	UIM_MOUSEMOVE,
	UIM_MOUSELEAVE,
	UIM_MOUSEENTER,

	UIM_TIMER,
	UIM_SWITCHENTER,
	UIM_SWITCHLEAVE,
	UIM_CREATE,
	UIM_OWNERDRAW,

	UIM_BUTTONDOWN_BEGIN,
	UIM_LBUTTONDOWN = UIM_BUTTONDOWN_BEGIN,
	UIM_RBUTTONDOWN,
	UIM_MBUTTONDOWN,

	UIM_BUTTONUP_BEGIN,
	UIM_LBUTTONUP = UIM_BUTTONUP_BEGIN,
	UIM_RBUTTONUP,
	UIM_MBUTTONUP,

};
#endif